--1.1
CREATE TABLE IF NOT EXISTS Members 
(
	MEMBER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30) NOT NULL,
	PHONE INTEGER,
	EMAIL VARCAHR(30),
	JOINING_DATE DATE,
	ENDING_DATE DATE 
);  
